server:
  port: 8000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: http://localhost:8771
          predicates:
            - Path=/a/**
          filters:
            - StripPrefix=1
        - id: host_route
          uri: http://localhost:8772
          predicates:
            - Path=/b/**
          filters:
            - StripPrefix=1
# Eureka配置
#eureka:
#  instance:
#    # eureka服务端的实例名称
#    hostname: client
#    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}:${random.value}
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#logging:
#  level:
#    org.springframework.cloud.gateway: debug